BraveMvc/Controllers/AllNewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using PagedList;
namespace BraveMvc.Controllers
{
    public class AllNewsController : Controller
    {
        // GET: AllNews
        public ActionResult Index(int?page)
        {
            var news = NewsManage.FindClassifyNews().Where(p=>p.Section_id==1).OrderByDescending(p=>p.SubmtDate);
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(news.ToPagedList(pageNumber, pageSize));
        }
    }
}

BraveMvc/Controllers/NewsShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BLL;
using PagedList;
using ViewModels;
using Models;

namespace BraveMvc.NewsControllers
{
    public class NewsShowController : Controller
    {
        // GET: News
        
        public ActionResult Index2()
        {
            
            var xiaoxi = NewsManage.FindAllNews().OrderByDescending(p=>p.SubmtDate).Take(6);
            var CountryNews = NewsManage.FindCountryNews().Where(p => p.Section_id == 1).Take(16);
            var InternationalNews = NewsManage.FindInternationalNews().Where(p => p.Section_id == 2).Take(16);
            var HotNews = NewsManage.FindHotNews().Where(p => p.Section_id == 3).Take(16);
            ViewModels.Cnpagelist index = new ViewModels.Cnpagelist();
            index.Findcountrynews = CountryNews;
            index.FindAllNews = xiaoxi;
            index.FindInternationalNews = InternationalNews;
            index.FindHotNews = HotNews;
            return View(index);
        }
        public ActionResult Detail(int id)
        {

            var detail = NewsManage.FindDetailNews(id);                       
            var FindBefore = NewsManage.FindDetailNews(id-1);
            var FindNext = NewsManage.FindDetailNews(id + 1);                     
            ViewModels.Cnpagelist index = new ViewModels.Cnpagelist();
            index.FindDetailNews = detail;         
            index.FindBefore = FindBefore;
            index.FindNext = FindNext;                       
            return View(index);
        }
        public ActionResult Details(string keyword)
        {

            var selectnews = NewsManage.SelectNews(keyword);
            return PartialView("Details",selectnews);
        }
       public ActionResult ClassifyNews()
        {
            var classify = NewsManage.FindClassifyNews().Where(p => p.Section_id == 1).OrderByDescending(p => p.News_id);                                                     
            return View(classify);
        }
        [HttpPost]
        public ActionResult Comment(CommentNews commentnews)
        {
            string content = Request["Newscomment"];
            int newsid = int.Parse(Request["Newsid"].ToString());
            int userid = int.Parse(Session["User_id"].ToString());
          
            if (content == null||content.Length==0)
           {
               return Content("<script>;alert('评论内容不能为空!');history.go(-1)</script>");
    }
            else if (ModelState.IsValid)
              {
                    commentnews.User_id = userid;
                    commentnews.News_id = newsid;
                    commentnews.Content = content;
                    commentnews.CommentTime = DateTime.Now;                 
                    CommentNewsManage.AddCommentNews(commentnews);
                    return Content("<script>;alert('评论成功!');history.go(-1)</script>");
                }
                     return RedirectToAction("Detail", "NewsShow");
           }
        }
}

BraveMvc/Views/NewsShow/ClassifyNews.cshtml
@using PagedList.Mvc;
@using Models
@{
    Layout = null;
}
<link href="~/Content/ClassifyNews.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClassifyNews</title>
</head>
<body>
   
   @{Html.RenderAction("Index", "AllNews");
   }


</body>
</html>

BraveMvc/Views/NewsShow/Detail.cshtml
@model ViewModels.Cnpagelist

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<link href="~/Content/NewsDetail.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detail</title>
</head>
<body>
    <div class="bigbox">
        <div class="content">
            <div class="detail-title"><h1>@Html.Raw(Model.FindDetailNews.NewsTitle)</h1></div>
            <div class="detail-daohang">
                <span>@Model.FindDetailNews.SubmtDate</span> <span>@Model.FindDetailNews.Author</span>               
            </div>
            <hr/>
            <p>@Html.Raw(@Model.FindDetailNews.NewsContent)</p>
            <div class="detail-comment">
                <div class="detail-commentHead">  
                    <h3>你想说点什么？</h3>                  
                    </div>
@using (Html.BeginForm("Comment", "NewsShow", FormMethod.Post))
{
                <div class="detail-commentTxt">
                  <div class="detail-commentTxtLeft">
                      @if (Session["User_id"] != null)
                      {
                          <img src="@Session["Image"]" />

                      }
                      else
                      {
                          <img src="~/Images/tc_login_yonghu.jpg" />
                      }
                  </div>
                <div class="detail-commentTxtRight">

    <input type="text" name="Newscomment" id="Newscomment" />
    <input type="hidden" value="@Model.FindDetailNews.News_id" name="Newsid" />



                </div>
                </div>
                    <div class="detail-commentSubmit">
                        <div class="detail-commentSubmitDiv">
                            @if (Session["User_id"] != null)
                            {
                                
                                <input type="submit" value="发表" />
                               
                            }
                            else
                            {
                                <a class="woyadengruaheahe">发表</a>
                            }
                        </div>
                    </div>
}
              <div class="detail-commentShow">
                <div class="detail-commentShowDiv"></div>
              </div>
             

            </div>
            <div class="contentBottom">
                <h2><a href="@Url.Action("Detail","NewsShow",new { id=@Model.FindBefore.News_id})">上一篇:@Model.FindBefore.NewsTitle</a></h2>
                <h2><a href="@Url.Action("Detail","NewsShow",new { id=@Model.FindNext.News_id})">下一篇:@Model.FindNext.NewsTitle</a></h2>
            </div>
        </div>
        <div class="detail-right">
            <form class="navbar-form navbar-left" action="@Url.Action("Details","NewsShow")">
                <div class="form-group">
                    <input type="text"  name="keyword" class="form-control" placeholder="Search    ">                   
                </div>
                <button id="btn1" class="btn btn-default">搜索新闻</button>
            </form>
           <div>
              
               <a id="text">@*@{Html.RenderAction("Details");}*@</a>
              <script type="text/javascript">
                  $(document).ready(function () {
                      $("#btn1").click(function () {
                          var kw=$("#keyword").val();
                          $.ajax({ 
                              type:"GET", //提交的类型 
                              url: '@Url.Action("Details","NewsShow")',//提交地址 
                              data:{keyword:kw},//参数 
                              success: function(data1){ //回调方法 
                                  //    $('#text').load('/Views/NewsShow/Details.cshtml'); 
                                  //} 
                                  $('#text').remove();
                                  $('#text').append("<span id='CheckCodeResult'>" + data1 + "</span>").css('color', '#1E90FF');
                              }
                          })
                      })
                  })
              </script>
           </div>
        </div>
    </div>
</body>
</html>

BraveMvc/Views/NewsShow/Details.cshtml
@model IEnumerable<Models.News>
@{
    ViewBag.Title = "Details";  
}
<link href="~/Content/NewsDetail.css" rel="stylesheet" />
<div class="select">
    <h2>搜索结果：</h2>
    <hr/>
    <ol>
        @foreach (var item in Model)
        {
            <li> <a href="@Url.Action("Detail","NewsShow",new { id=@item.News_id})">@item.NewsTitle;</a></li>
        }
    </ol>
</div>

BraveMvc/Views/NewsShow/Index2.cshtml
@using Models
@model ViewModels.Cnpagelist
@{
    ViewBag.Title = "Index2";
   
}
<link rel="stylesheet" type="text/css" href="~/Content/NewsShow.css" />
<script src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
<script src="~/Scripts/banner.js"></script>
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/jquery.carousel.js"></script>
<link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/IndexFloat.css" rel="stylesheet" />
<script>   
    $(function(){
        $(".bellows__content-wrapper").hide();
        $(".bellows__header").click(function(){
            $(this).next().slideDown()
            $(this).parent(".bellows__item").addClass("bellows--is-open")
            $(".bellows__header").not(this).next().slideUp()
            $(".bellows__header").not(this).parent(".bellows__item").removeClass("bellows--is-open")
        })
    })
</script>

<body><div class="slide">
    <ul class="icon">
        <li class="up" title="上一页"></li>
        <li class="qq"></li>
        <li class="tel"></li>
        <li class="wx"></li>
        <li class="down" title="下一页"></li>
    </ul>
    <ul class="info">
        <li class="qq">
            <p>在线沟通，请点我<a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes" target="_blank">在线咨询</a></p>
        </li>
        <li class="tel">
            <p>咨询热线：<br>400-800-8888<br>客服qq：<br>123456789</p>
        </li>
        <li class="wx">
            <div class="img">
                <img src="~/Images/float/1441956938.png" />
            </div>
        </li>
    </ul>
</div>
<div id="btn" class="index_cy"></div>

<script type="text/javascript">
$(function(){

	$('.slide .icon li').not('.up,.down').mouseenter(function(){
		$('.slide .info').addClass('hover');
		$('.slide .info li').hide();
		$('.slide .info li.'+$(this).attr('class')).show();//.slide .info li.qq
	});
	$('.slide').mouseleave(function(){
		$('.slide .info').removeClass('hover');
	});

	$('#btn').click(function(){
		$('.slide').toggle();
		if($(this).hasClass('index_cy')){
			$(this).removeClass('index_cy');
			$(this).addClass('index_cy2');
		}else{
			$(this).removeClass('index_cy2');
			$(this).addClass('index_cy');
		}

	});

});
</script>
    <div class="all">
        <div class="pictureShow">
            <div class="banner">
                <div class="b-img">
                    @foreach (News item in Model.FindAllNews)
                    {
                        <a href="@Url.Action("Detail","NewsShow",new { id=@item.News_id})"  ><img src="@item.NewsPicture" style="height:100%;width:100%;"/></a>
                    }


                </div>
                <div class="b-list"></div>
                <a class="bar-left" href="#"><em></em></a><a class="bar-right" href="#"><em></em></a>
            </div>
        </div>
        <div class="pictureShowtitle">
           <h3>图说天下</h3>
        </div>
            <div class="pictureWorld">
                <div class="demo">

                    <div class="container">

                        <div class="row">
                            @foreach (var item in Model.FindAllNews)
                        {
                                <div class="col-md-4 col-sm-6">
                                    <div class="box">
                                        <div class="box-img">
                                            <img src="@item.NewsPicture" alt="" />
                                        </div>
                                        <div class="box-content">
                                            <h4 class="title">@item.NewsTitle</h4>
                                            <p class="description"><a href="@Url.Action("Detail","NewsShow",new {id=@item.News_id })">查看更多</a></p>
                                            <ul class="social-links">
                                                <li><a href="#" class="fa fa-qq"></a></li>
                                                <li><a href="#" class="fa fa-weibo"></a></li>
                                                <li><a href="#" class="fa fa-weixin"></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                        }
                        </div>
                    </div>
                </div>
            </div>
      
        <div class="bellows single">
            <div class="bellows__item">
                <div class="bellows__header">
                    <h3><a href="@Url.Action("ClassifyNews","NewsShow")">国内新闻</a></h3>
                </div>
                <div class="bellows__content-wrapper">
                    <div class="bellows__content">
                        <div style="width:90%;float:left;column-count:2;column-gap:5em;">
                            @foreach (News item in Model.Findcountrynews)
                            {
                                <a href="@Url.Action("Detail","NewsShow", new { id=@item.News_id})"><p> @item.NewsTitle</p></a>
                            }
                        </div>
                        <div class="skip">
                        <a href="@Url.Action("ClassifyNews","NewsShow", new { id=1})">更多内容>>></a>   
                        </div> 
                            
                </div>
                </div>
            </div>
            <div class="bellows__item">
                <div class="bellows__header">
                    <h3><a href="@Url.Action("Index","AllNews", new { id=2})">国际新闻</a></h3>
                </div>
                <div class="bellows__content-wrapper">
                    <div class="bellows__content">
                        
                        <div style="width:90%;float:left;column-count:2;column-gap:5em;">
                            @foreach (News item1 in Model.FindInternationalNews)
                            {
                                <a href="@Url.Action("Detail","NewsShow", new { id=@item1.News_id})"><p> @item1.NewsTitle</p></a>
                            }
                            </div>
                         <div class="skip">
                                <a href="@Url.Action("ClassifyNews","NewsShow", new { id=2})">更多内容>>></a>
                            </div>


                        </div>
                </div>
            </div>
            <div class="bellows__item">
                <div class="bellows__header">
                    <h3><a href="@Url.Action("Index","AllNews", new { id=3})">地区热点</a></h3>
                </div>
                <div class="bellows__content-wrapper">
                    <div class="bellows__content">
                        <div style="width:90%;float:left;column-count:2;column-gap:5em;">
                            @foreach (News item2 in Model.FindHotNews)
                            {
                                <a href="@Url.Action("Detail","NewsShow",new { id=@item2.News_id})"><p> @item2.NewsTitle</p></a>
                            }
                            </div>
                            <div class="skip">
                                <a href="@Url.Action("ClassifyNews","NewsShow", new { id=3})">更多内容>>></a>
                            </div>
                        </div>
                </div>
            </div>

        </div>
        

    </div>
    <div class="index-video">
   @foreach (var item in Model.FindHotNews)
   {
       <div>
           <a href="http://tv.cctv.com/2017/05/06/VIDECcM8XahvQ1XsrrtmvN1Y170506.shtml"><h4>@item.NewsTitle</h4>
               <img src="@item.NewsPicture" /></a>
           
       </div>
   }
    </div>

   
   
   
</body>