BraveMvc/ViewModels/SelectGoods.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Models;

namespace ViewModels
{
    public class SelectGoods
    {
        public IEnumerable<Goods> good1 { get; set; }
        public IEnumerable<Goods> good2 { get; set; }
    }
}

BraveMvc/Controllers/AllGoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using BLL;
using Models;
using DAL;
using IDAL;
using DALFactory;
using ViewModels;


namespace BraveMvc.Controllers
{
    public class AllGoodsController : Controller
    {
        // GET: AllGoods
        public ActionResult Index(String classifyInfoFrom, String SortInfoFrom, string currentFilter, int? page)
        {
           

        

            var goods = GoodsManage.FindGoods();

            if (classifyInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                classifyInfoFrom = currentFilter;
            }

            ViewBag.CurrentFilter = classifyInfoFrom;
            if (SortInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                SortInfoFrom = currentFilter;
            }
            ViewBag.CurrentFilter = SortInfoFrom;

            if (!string.IsNullOrEmpty(classifyInfoFrom))  //注意，判断字符串类型为空，要使用String.IsNullEmpty() 而不能使用 !=null 来判断。
            {
                goods = goods.Where(x => x.Classify.ClassifyName == classifyInfoFrom);
            }
            //ViewBag.searchString = searchString;
            if (!String.IsNullOrEmpty(SortInfoFrom))
            {
                if (SortInfoFrom == "价格降序")
                {
                    goods = goods.OrderByDescending(p => p.GoodsPrice);
                }
                else if (SortInfoFrom == "价格升序")
                {
                    goods = goods.OrderBy(p => p.GoodsPrice);
                }
                else if (SortInfoFrom == "更新时间")
                {
                    goods = goods.OrderByDescending(p => p.Grounding);
                }


            }

            int pageSize = 9;
            int pageNumber = (page ?? 1);

            return View(goods.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Classify(String classifyInfoFrom, String SortInfoFrom, string currentFilter, int? page)
        {
            var clas = ClassifyManage.FindAllClassify();
            var goods = GoodsManage.FindGoods();
            if (page == null)
            {
                page = 1;
            }
            if (classifyInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                classifyInfoFrom = currentFilter;
            }
            ViewBag.CurrentFilter = classifyInfoFrom;
            if (SortInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                SortInfoFrom = currentFilter;
            }
            ViewBag.CurrentFilter = SortInfoFrom;

            if (!String.IsNullOrEmpty(classifyInfoFrom))
            {

                goods = goods.Where(x => x.Classify.ClassifyName == classifyInfoFrom);

            }
            if (!String.IsNullOrEmpty(SortInfoFrom))
            {
                goods = goods.OrderByDescending(p => p.GoodsPrice);
            }

            int pageSize = 9;
            int pageNumber = (page ?? 1);
            ViewModels.Clasaifymenu clmenu = new ViewModels.Clasaifymenu();
            clmenu.Classify1 = clas;
            clmenu.Goodsss = goods.ToPagedList(pageSize, pageNumber);

            return View("Classify", clmenu);
          
        }
    }
}

BraveMvc/Controllers/MallsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using BLL;
using System.Net;
using Models;
using DAL;
using IDAL;
using DALFactory;
using ViewModels;
using System.Data.Entity.Validation;



namespace BraveMvc.Controllers
{
  
    public class MallsController : Controller
    {
        // GET: Malls
       
        public ActionResult Index()
        {
            var good=GoodsManage.FindAllBooks().OrderByDescending(p => p.Grounding).Take(8);
            var Zhanji = GoodsManage.FindAllBooks().Where(b => b.Classify_id == 1).Take(6);
            var Qiang = GoodsManage.FindAllBooks().Where(c => c.Classify_id == 4).Take(12);
            var Hangmu = GoodsManage.FindAllBooks().Where(a => a.Classify_id == 3).Take(6);
            var Feixing = GoodsManage.FindAllBooks().Where(d => d.Classify_id == 2).Take(6);
            var Tanke = GoodsManage.FindAllBooks().Where(e => e.Classify_id == 8).Take(6);
         
            ViewModels.Goodss index = new ViewModels.Goodss();
            index.Good6 = good;
            index.Good1 = Zhanji;
            index.Good2 = Qiang;
            index.Good3 = Hangmu;
            index.Good4 = Feixing;
            index.Good5 = Tanke; 


            return View(index);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        /// 
        public ActionResult aboutss()
        {
            return View();
        }
      
        public ActionResult Classify(String classifyInfoFrom, String SortInfoFrom, string currentFilter, int page=1)
        {
            var clas = ClassifyManage.FindAllClassify();
            var goods = GoodsManage.FindGoods();
           
         
            if (classifyInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                classifyInfoFrom = currentFilter;
            }
            ViewBag.CurrentFilter = classifyInfoFrom;
            if (SortInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                SortInfoFrom = currentFilter;
            }
            ViewBag.CurrentFilter = SortInfoFrom;

            if (!String.IsNullOrEmpty(classifyInfoFrom))
            {

                goods = goods.Where(x => x.Classify.ClassifyName == classifyInfoFrom);

            }
            if (!String.IsNullOrEmpty(SortInfoFrom))
            {
                if (SortInfoFrom == "价格降序")
                {
                    goods = goods.OrderByDescending(p => p.GoodsPrice);
                }
                else if(SortInfoFrom == "价格升序")
                {
                    goods = goods.OrderBy(p => p.GoodsPrice);
                }
                
                else if (SortInfoFrom == "更新时间")
                {
                    goods = goods.OrderByDescending(p => p.Grounding);
                }
              

            }

            const int pageSize = 10;

            ViewModels.Clasaifymenu clmenu = new ViewModels.Clasaifymenu();
            clmenu.Classify1 = clas;
            clmenu.Goodsss = goods.ToPagedList(page, pageSize);
         


            return View("Classify", clmenu);
        }
        //详情
        public ActionResult Detail(int id,int classid)
        {

            var good = GoodsManage.Getgood(id);
            var classif = GoodsManage.FindAllBooks().Where(p => p.Classify_id == classid);
            var Comment = CommentGoodsManage.findallcomment(id);
        
            if (good == null)
            {
                return HttpNotFound();
            }
            if (classif == null)
            {
                return HttpNotFound();
            }
            if (Comment == null)
            {
                return HttpNotFound();
            }
            ViewModels.GoodsDetail index = new GoodsDetail();
            index.Goodss = good;
            index.Goods11 = classif;
            index.Comment1 = Comment;
          
            return View(index);
            //return View();
        }
        [HttpPost]
        public ActionResult addComment(CommentGoods comgoods)
        {
            string content = Request["detail-goods-comment"];
            int goodsid = int.Parse(Request["detail-goodsName"].ToString());
            int userid = int.Parse(Session["User_id"].ToString());
            if (content == null||content.Length==0)
            {
                return Content("<script>;alert('评论内容不能为空!');history.go(-1)</script>");
            }
            else if (ModelState.IsValid)
              {
                    comgoods.User_id = userid;
                    comgoods.Goods_id = goodsid;
                    comgoods.Content = content;
                    comgoods.CommentTime = DateTime.Now;
                    CommentGoodsManage.AddCommentGoods(comgoods);
                    return Content("<script>;alert('评论成功!');history.go(-1)</script>");
               }
           
          
            return RedirectToAction("Detail", "Malls");


        }
        public ActionResult Reply()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Reply(ReplyGoods repgoods)
        {
            string reply = Request["replaygoods"];
            int commid = Convert.ToInt32(Request["commendid"]);
            int userid = Convert.ToInt32(Session["User_id"]);
            var replylist = CommentGoodsManage.findallreply(commid);
            if (reply == null)
            {
                return Content("<script>;alert('回复内容不能为空!');history.go(-1)</script>");
            }
            else if (ModelState.IsValid)
            {
                repgoods.CommentGoods_id = commid;
                repgoods.User_id = userid;
                repgoods.Content = reply;
                repgoods.ReplyTime = DateTime.Now;
                CommentGoodsManage.addReplyGoods(repgoods);
                return Content("<script>;alert('回复成功!');history.go(-1)</script>");
            }
                return RedirectToAction("Detail", "Malls");
        }
      
        public ActionResult SelectReply(int commendid)
        {
            var replydf = CommentGoodsManage.findallreply(commendid);
            ViewModels.GoodsDetail der = new GoodsDetail();
            der.Reply1 = replydf;
            return View(der);
        }


        public ActionResult selectGood(string searchString,string SortInfoFrom)
        {
            var good = GoodsManage.selectGoods();
            var tugood = GoodsManage.FindGoods().Take(3);
            if (!String.IsNullOrEmpty(searchString))
            {
                good = good.Where(s => s.GoodsDes.Contains(searchString));
            }
            if (!String.IsNullOrEmpty(SortInfoFrom))
            {
                if (SortInfoFrom == "价格降序")
                {
                    good = good.OrderByDescending(p => p.GoodsPrice);
                }
                else if (SortInfoFrom == "价格升序")
                {
                    good = good.OrderBy(p => p.GoodsPrice);
                }

                else if (SortInfoFrom == "更新时间")
                {
                    good = good.OrderByDescending(p => p.Grounding);
                }

            }
                SelectGoods inde = new SelectGoods();
            inde.good1 = good;
            inde.good2 = tugood;
            return View(inde);
        }
    }
}

BraveMvc/Views/Malls/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = null;
}

BraveMvc/Views/Malls/Classify.cshtml
@using Models
@model ViewModels.Clasaifymenu

@using X.PagedList
@using PagedList.Mvc;
@{
    ViewBag.Title = "Classify";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";


}
@Styles.Render("~/Content/Malls.css")
@Styles.Render("~/Content/bootstrap.css")
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/jquery-3.1.1.min.js"></script>

<script src="~/Scripts/bootstrap.min.js"></script>

<style>
    .imgmaclarge{
        display:block;
         margin-left:30%
    }
</style>
<div class="container classify-quanbu">
    <div class="row classify-weizhi">
        <span>当前位置>>虎贲商城>>分类</span>
    </div>
    <div class="row classify-fenlei">
       <div class="col-xs-4 col-sm-3 col-md-3 classify-title">
        
               @Ajax.ActionLink("全部商品模型", "Classify", "Malls", null)
               @foreach (Classify c in Model.Classify1)
               {
                @Ajax.ActionLink(c.ClassifyName, "Classify", "Malls", new {classifyInfoFrom = c.ClassifyName }, new AjaxOptions()
               {
                   UpdateTargetId = "classifywuping",
                  
               })
               
               }
          
       </div>
        <div class="col-xs-8 col-sm-9 col-md-9 classify-paixuwuping">
            <div class="row classify-paixu">
                <p>商品筛选</p>
                <div class="col-xs-3 col-sm-6 col-md-6"></div>
                
                    <div class="col-xs-3 col-sm-2 col-md-2 classify-paixu-jiage">
                        @Ajax.ActionLink("价格", "Classify", "Malls", new { SortInfoFrom = "价格降序" }, new AjaxOptions()
               {
                   UpdateTargetId = "classifywuping",
                   InsertionMode = InsertionMode.Replace,
                   HttpMethod = "GET"
               })
                        <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
                    </div>
                <div class="col-xs-3 col-sm-2 col-md-2 classify-paixu-jiage">
                    @Ajax.ActionLink("价格", "Classify", "Malls", new { SortInfoFrom = "价格升序" }, new AjaxOptions()
           {
               UpdateTargetId = "classifywuping",
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "GET"
           })
                    <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-2 classify-paixu-jiage">
                    @Ajax.ActionLink("更新时间", "Classify", "Malls", new { SortInfoFrom = "更新时间" }, new AjaxOptions()
               {
                   UpdateTargetId = "classifywuping",
                   InsertionMode = InsertionMode.Replace,
                   HttpMethod = "GET"
               })
                    <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
                </div>

            
         @{Html.RenderAction("Index", "AllGoods");}
       
        </div>
       
    </div>
</div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")



<script type="text/javascript">
    //$(".classify-wuping-img").hover(function () {
    //    $("#largeimg").addClass("imgmaclarge")
       
    //},
    //function () {
    //    $("#largeimg").removeClass("imgmaclarge")
    //}
    //)

    
</script>

BraveMvc/Views/Malls/Reply.cshtml
@using Models
@model ViewModels.GoodsDetail
@{
    ViewBag.Title = "Reply";
    Layout = null;
}


    @foreach (ReplyGoods m in Model.Reply1)
    {
        <div class="row comment-qunbu-mouren">
            <img src="@m.Users.UserImage" />

            <span style="font-size:x-large">@m.Users.UserName</span>
            <span>发表于</span>
            <span>@m.ReplyTime</span>
            <p>@m.Content</p>
     </div>
    }

    @*@using (Html.BeginForm("Reply", "Malls", FormMethod.Post, new { id = "addReply" }))
            {
                <div class="col-sm-2 col-md-2"></div>
                <div class="col-xs-12 col-sm-9 col-md-9 reply-detail-more">
                    <textarea name="replaygoods"></textarea>


                </div>
                <div class="col-sm-1 col-md-1 btn-reply">
                    <a href="javascript:document.getElementById('addReply').submit()">回复</a>
                </div>
            }*@
        

BraveMvc/Views/Malls/SelectReply.cshtml
@using Models
@model ViewModels.GoodsDetail
@{
    ViewBag.Title = "SelectReply";
    Layout = null;
}
@*<div class="row reply-detail-goods" id="chakangeng">*@
<div>
    @foreach (ReplyGoods m in Model.Reply1)
    {
        <div class="row comment-qunbu-mouren">
            <img src="@m.Users.UserImage" />

            <span style="font-size:x-large">@m.Users.UserName</span>
            <span>回复</span>
            <span>@m.ReplyTime</span>
            <p>@m.Content</p>
        </div>
    }
</div>
 @*</div>*@

BraveMvc/Views/Malls/aboutss.cshtml
@{
    ViewBag.Title = "aboutss";
    Layout = null;
}

<div id="app">
    {{ message }}
</div>
<div id="app-2">
    <span v-bind:title="message">
        鼠标悬停几秒钟查看此处动态绑定的提示信息！
    </span>
  </div>
<script src="~/Scripts/vue.min.js"></script>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            message: 'Hello Vue!'
        }
    })
    var app2 = new Vue({
        el: '#app-2',
        data: {
            message: '页面加载于 ' + new Date()
        }
    })
</script>

BraveMvc/Views/Malls/selectGood.cshtml
@using Models
@model ViewModels.SelectGoods

@{
    ViewBag.Title = "selectGood";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
@Styles.Render("~/Content/Carts.css")
<div class="container">
    <div class="row setect-weizhi">
        当前位置>>商城>>搜索
    </div>
   
   <div class="row">
            <div class="col-xs-12 col-sm-9 col-md-9 select-filter">
                <p>商品筛选</p>

                <div class="row select-Title">
                    <div class="col-xs-3 col-sm-2 col-md-2 select-fliter-sdw">
                     
                        @Ajax.ActionLink("综合排序", "selectGood", "Malls", null)
                    </div>
                    <div class="col-xs-3 col-sm-2 col-md-2 classify-paixu-jiage">
                        @Ajax.ActionLink("价格", "selectGood", "Malls", new { SortInfoFrom = "价格降序"}, new AjaxOptions()
                   {
                       UpdateTargetId = "dsjdwiefDsdwe",
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET"
                   })
                        <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
                    </div>
                    <div class="col-xs-3 col-sm-2 col-md-2 classify-paixu-jiage">
                        @Ajax.ActionLink("价格", "selectGood", "Malls", new { SortInfoFrom = "价格升序" }, new AjaxOptions()
           {
               UpdateTargetId = "dsjdwiefDsdwe",
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "GET"
           })
                        <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                    </div>
                    <div class="col-xs-3 col-sm-2 col-md-2 classify-paixu-jiage">
                        @Ajax.ActionLink("更新时间", "selectGood", "Malls", new { SortInfoFrom = "更新时间" }, new AjaxOptions()
           {
               UpdateTargetId = "dsjdwiefDsdwe",
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "GET"
           })
                        <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
                    </div>

                    <div class="col-sm-4 col-md-4"></div>

                </div>
                <div class="row select-good">
                    @foreach (Goods m in Model.good1)
                    {
                        <div class="col-xs-12 col-sm-3 col-md-3">
                            <div class="select-filter-goods">
                                <a href="@Url.Action("Detail","Malls", new { id = @m.Goods_id,classid=@m.Classify_id })">
                                    <div class="select-goods-img">

                                        <img src="@m.GoodsImage1" class="fangdatupian" />
                                    </div>
                                    <div class="select-goods-dect">
                                        <p>@m.GoodsName</p>
                                        <div class="col-xs-6 col-sm-6 col-md-6" style="color:red">￥@m.GoodsPrice</div>
                                        <div class="col-xs-6 col-sm-6 col-md-6"style="color:#c0c0c0;text-align:right">
                                       师大
                                        </div>
                                       
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
       <div class="col-sm-3 col-md-3 select-recommend">
           <div class="row" style="color:black;box-shadow:0 5px 4px #c6c6c6;text-align:center">平台热卖</div>
           <div class="row select-tuijian">
               @foreach (Goods n in Model.good2)
               {
                <div class="select-recommend-img">
                    <a href="@Url.Action("Detail","Malls", new { id = @n.Goods_id,classid=@n.Classify_id })">
                        <img src="@n.GoodsImage1" />
                        <div class="row select-recommend-title">
                            <h4>@n.GoodsName</h4>
                            <div class="col-xs-6 col-sm-6 col-md-6">￥@n.GoodsPrice</div>
                            <div class="col-xs-6 col-sm-6 col-md-6" style="color:#c6c6c6;text-align:right">已售82件</div>
                        </div>
                    </a>
                </div>
               }
             
           </div>
       </div>
             
        </div>
    

</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">
    //var sdde = $(".classify-paixu-jiage")
    //sdde.children().click(function () {
    //    $(this).css({
    //        'color': 'red'
    //    })
    //    $(this).parent().css({
    //        'border': '1px solid #c6c6c6'
    //    })
    //    $(this).siblings().css({
    //        'color': 'red'
    //    })
    //})
</script>